### ISSUE TITLE
网址采集，第四个疑问。

### ISSUE THREAD

**Issue by Homework-DAD** [foxwhite25/megaCrawler#116]
# 网站
菲律宾健康保险公司

# 网址
https://www.philhealth.gov.ph/

# 问题
没有采集到文章（以下视频为运行1714.go的情况）
https://github.com/user-attachments/assets/4c31fb57-f6b6-42d9-b416-4e6ac139aa22

# 附件
```go
package dev

import (
	"megaCrawler/crawlers"
	"megaCrawler/extractors"

	"github.com/gocolly/colly/v2"
)

func init() {
	engine := crawlers.Register("1714", "菲律宾健康保险公司", "https://www.philhealth.gov.ph/")

	engine.SetStartingURLs([]string{"https://www.philhealth.gov.ph/news/up/article/2024/archives.php"})

	extractorConfig := extractors.Config{
		Author:       true,
		Image:        true,
		Language:     true,
		PublishDate:  true,
		Tags:         true,
		Text:         true,
		Title:        true,
		TextLanguage: "",
	}

	extractorConfig.Apply(engine)

	engine.OnHTML(".lselect2 > ul > li > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		engine.Visit(element.Attr("href"), crawlers.News)
	})

	// engine.OnHTML("#main_bod > div.right_con > ul > li:nth-child(1) > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
	// 	engine.Visit(element.Attr("href"), crawlers.Index)
	// })
	// 2023年及以后的链接全部为pdf文件下载，没用。

}
```

**Comment by Homework-DAD** [comment]
在浏览器里查看了一下，发现网站给的href的链接不全，浏览器会自动补全，但脚本不能，导致无法访问到正确的地址。
比如在浏览器中href="news_66a6f363f10b0.php"
新闻链接为：https://www.philhealth.gov.ph/news/up/article/2024/news_66a6f363f10b0.php
脚本实际访问的：https://www.philhealth.gov.ph/news_66a6f363f10b0.php

**Comment by Homework-DAD** [comment]
这个我问了灿成，他说要用json，我等会找林老师要回放，如果实在不行的话，请学长指点一下。

**Comment by foxwhite25** [comment]
> 在浏览器里查看了一下，发现网站给的href的链接不全，浏览器会自动补全，但脚本不能，导致无法访问到正确的地址。 比如在浏览器中href="news_66a6f363f10b0.php" 新闻链接为：https://www.philhealth.gov.ph/news/up/article/2024/news_66a6f363f10b0.php 脚本实际访问的：https://www.philhealth.gov.ph/news_66a6f363f10b0.php

因为网站用的是相对地址，本来是需要自己进行解析的
https://github.com/foxwhite25/megaCrawler/blob/b9d4aeee8c9b68c928ea777797b5f122c992a02b/plugins/production/nids.go#L53-L58

但我想到了一个更好的方法，你可以pull一下然后使用 ctx.Visit 直接一步搞定

**Comment by foxwhite25** [comment]
关于“2023年及以后的链接全部为pdf文件下载，没用“，这里可以使用Report页面类型，Report只需要Content或者File不为空即可，代表了报告

**Comment by Homework-DAD** [comment]
不行，2023年以后的链接是空内容（只是一个pdf下载链接）
<img width="1280" alt="1714-Log" src="https://github.com/user-attachments/assets/24913812-02c2-4287-aa9d-37c38b307a6f">
