### ISSUE TITLE
关于动态加载的问题

### ISSUE THREAD

**Issue by Terminal017** [foxwhite25/megaCrawler#118]
# 网站 URL
- 网站 URL: `https://www.52hrtt.com/ey/n/w`
- 网站 ID: `1102`

# 复现步骤
1. 使用爬虫初始化爬取 `https://www.52hrtt.com/ey/n/w`。
2. 运行爬虫后，发现只能采集到前几篇文章，无法获取更多内容，猜测可能与**页面滚动的动态加载**有关。

# 最小的复现代码

```go
package dev

import (
	"megaCrawler/crawlers"
	"megaCrawler/extractors"

	"github.com/gocolly/colly/v2"
)

func init() {
	engine := crawlers.Register("1102", "华人头条", "https://www.52hrtt.com/ey/n/w")

	engine.SetStartingURLs([]string{"https://www.52hrtt.com/ey/n/w"})

	extractorConfig := extractors.Config{
		Author:       true,
		Image:        true,
		Language:     true,
		PublishDate:  true,
		Tags:         true,
		Text:         false,
		Title:        true,
		TextLanguage: "",
	}

	extractorConfig.Apply(engine)

	engine.OnHTML("div.item_right > div > h3 > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		engine.Visit(element.Attr("href"), crawlers.News)
	})

	engine.OnHTML(".video-box > div > p", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Content += element.Text

	})
}

```

# 问题所在
对于这种问题，该如何解决？比如说让爬虫引擎模拟滚动的操作，是否可行？

# 核对清单

- [ x] 如果是关于如何进入入口的问题，我已经确认该网站并没有 sitemap。

# 额外背景
补充图片：
![1723998928595](https://github.com/user-attachments/assets/2aba01e5-4dda-4d1d-9868-12d60668ddcc)
![1723999029311](https://github.com/user-attachments/assets/049ddd54-475b-4fd7-ba9c-23b21a942033)

**Comment by foxwhite25** [comment]
网页是通过api获取数据的

https://www.52hrtt.com/s/webapi/ey/n/w?parameterJson=%7B%22recommendParamsMap%22:%7B%22size%22:20,%22from%22:0%7D%7D
