### ISSUE TITLE
关于动态内容的网站以及Ajax请求

### ISSUE THREAD

**Issue by Terminal017** [foxwhite25/megaCrawler#122]
# 网站 URL
- 主网站：https://www.quotemedia.com/
- 采集的目标网站：https://research.quotemedia.com/home/news?symbol=NEWS

# 问题
1、这个网站采用动态内容设计，要获取这个网站的新闻链接，需要先点击一个链接（如图1），才会跳出一个有链接的页面（如图2）。
2、询问一下该如何解决链接的索引问题。
3、学长可否教一下**如何根据网站的AJAX请求进行采集**；或者可不可以给一个实例代码。

```go
package dev

import (
	"megaCrawler/crawlers"
	"megaCrawler/extractors"

	"github.com/gocolly/colly/v2"
)

func init() {
	engine := crawlers.Register("1421", "市场新闻公报", "https://www.quotemedia.com/")

	engine.SetStartingURLs([]string{"https://www.quotemedia.com/portal/news?qm_symbol=NEWS"})

	extractorConfig := extractors.Config{
		Author:       true,
		Image:        true,
		Language:     true,
		PublishDate:  true,
		Tags:         true,
		Text:         false,
		Title:        true,
		TextLanguage: "",
	}

	extractorConfig.Apply(engine)

	engine.OnHTML(".qmod-news-list > li > div > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		engine.Visit(element.Attr("href"), crawlers.News)
	})

	engine.OnHTML(".qmod-ui-modal-body > div > div > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		engine.Visit(element.Attr("href"), crawlers.News)
	})

	engine.OnHTML(".news-article", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Content += element.Text
	})
}

```

# 核对清单
- [ x] 如果是关于如何进入入口的问题，我已经确认该网站并没有 sitemap。

# 额外背景
补充图片：
![1725534017802](https://github.com/user-attachments/assets/7a2d5732-49b5-4755-ab79-e4082ff959ec)
![1725534143513](https://github.com/user-attachments/assets/70cccea4-8d73-4707-9e38-f6bba5c3afc3)

**Comment by foxwhite25** [comment]
你确定这真的智库吗，这是个股票新闻查询网站啊，你这个News是一个名为NewStar Financeial Inc.的公司

**Comment by foxwhite25** [comment]
ajax例子
https://github.com/foxwhite25/megaCrawler/blob/de0f9ba7e114dd306fc995f03f8c8dba7dc8f750/plugins/production/rusi.go#L292-L336

**Comment by Terminal017** [comment]
了解了学长
