### ISSUE TITLE
问题（10.20）

### ISSUE THREAD

**Issue by GUshouCHUANwei** [foxwhite25/megaCrawler#135]
# 网站 URL

https://nationalinterest.org
https://nationalinterest.org/commentary/high-time-obama-syria-strategy-8976
第二个网址是存在翻页的具体文章页

# 复现步骤

通过sitemap发现该网站部分文章存在翻页键
![屏幕截图 2024-10-20 100107](https://github.com/user-attachments/assets/7e32a1a9-e111-4465-9084-bfb7331720ec)

# 最小的复现代码

现在还没有写脚本，因为文章里面存在翻页键这种情况，我显然不会。

# 问题所在

想问学长，因为该网站不是所有文章都有翻页键，可不可以写出一个脚本，当文章里存在翻页键时，能够检测并跳到下一页直到采完文章内容
# 核对清单

- [ ] 如果是关于如何进入入口的问题，我已经确认该网站并没有 sitemap。

# 额外背景

**Comment by foxwhite25** [comment]
自己http.Get访问一下，然后用goquery把剩下的部分获取到呗，类似这样
https://github.com/foxwhite25/megaCrawler/blob/20f13d6fc8f46c6cbb28f951f5270e7848fde3c8/plugins/production/1078.go#L30-L59
