### ISSUE TITLE
关于网站合并的问题

### ISSUE THREAD

**Issue by Terminal017** [foxwhite25/megaCrawler#139]
#问题
1、采集网站自编号597往后的网站均属于英国政府主域名 www.gov.uk ，每个网站对应的是该域名+对应的部门标签（如https://www.gov.uk/government/organisations/department-for-work-pensions ）
图例：
![屏幕截图 2024-10-29 210545](https://github.com/user-attachments/assets/feaa31a8-b089-414a-8ff9-37f4e4ab7932)
Tip：这里原本不是的也已经被英国政府合并了。

2、这里应该可以通过主域名采集所有的新闻： https://www.gov.uk/search/news-and-communications （或用sitemap）；也可以分开采集包含各个部门标签的新闻：如  https://www.gov.uk/search/news-and-communications?organisations[]=department-for-work-pensions&parent=department-for-work-pensions 。

3、询问一下这里是否需要保留各个部门的标签分开采集，还是合并作为一个主网站采集？

**Comment by foxwhite25** [comment]
问老师
