### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by Homework-DAD** [foxwhite25/megaCrawler#140]
# 网站
http://www.rmhb.com.cn/

# 问题
文章来源：站内和微信公众号。
请问如何合并class？
<img width="1280" alt="问题1-1" src="https://github.com/user-attachments/assets/8a228d94-b883-44fa-8c4a-26be0b16423e">
<img width="1280" alt="问题1-2" src="https://github.com/user-attachments/assets/7809a97d-baf8-4420-96c8-20995171f107">
<img width="1280" alt="问题1-3" src="https://github.com/user-attachments/assets/a4fd6d0d-69a8-4919-8205-a41634351382">

# 脚本
package dev

import (
	"megaCrawler/crawlers"
	"megaCrawler/extractors"

	"github.com/gocolly/colly/v2"
)

func init() {
	engine := crawlers.Register("1776", "人民画报", "http://www.rmhb.com.cn/")

	engine.SetStartingURLs([]string{
		"http://www.rmhb.com.cn/yw/",
		"http://www.rmhb.com.cn/gz/",
		"http://www.rmhb.com.cn/sh/",
		"http://www.rmhb.com.cn/kzg/",
		"http://www.rmhb.com.cn/xyd/",
		"http://www.rmhb.com.cn/gd/",
		"http://www.rmhb.com.cn/hbzx/",
	})

	extractorConfig := extractors.Config{
		Author:       true,
		Image:        true,
		Language:     true,
		PublishDate:  true,
		Tags:         true,
		Text:         false,
		Title:        true,
		TextLanguage: "",
	}

	extractorConfig.Apply(engine)

	engine.OnHTML(".two-level-left.politic-left.display-n > div > h2 > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Visit(element.Attr("href"), crawlers.News)
	})
	// 站内文章
	engine.OnHTML(".Custom_UnionStyle", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Content += element.Text
	})
	// 微信公众号文章
	engine.OnHTML(".rich_media_content", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Content += element.Text
	})

	engine.OnHTML(".page-list > p:nth-last-child(1) > a", func(element *colly.HTMLElement, ctx *crawlers.Context) {
		ctx.Visit(element.Attr("href"), crawlers.Index)
	})
}

**Comment by foxwhite25** [comment]
为什么要合并

**Comment by Homework-DAD** [comment]
又出现了一个问题：
用two-level-left.politic-left.display-n > div > h2 > a选择器在网页能够匹配所有新闻网站，但实际采集的时候无法匹配到所有属于微信的网站。
